# ValidationHelper.ExecuteWithCatchExceptionAsync - метод
##  __Список перегрузок
[ExecuteWithCatchExceptionAsync(Func<CancellationToken, Task>,
CancellationToken)](M_Tessa_Applications_ValidationHelper_ExecuteWithCatchExceptionAsync.htm)|
Выполняет actionAsync и возникшие исключения помещает в
[ValidationResult](T_Tessa_Platform_Validation_ValidationResult.htm)  
---|---  
[ExecuteWithCatchExceptionAsync<T>(Func<CancellationToken, Task<T>>,
CancellationToken)](M_Tessa_Applications_ValidationHelper_ExecuteWithCatchExceptionAsync__1.htm)|
Выполняет funcAsync и возникшие исключения помещает в
[ValidationResult](T_Tessa_Platform_Validation_ValidationResult.htm)  
##  __См. также
#### Ссылки
[ValidationHelper - ](T_Tessa_Applications_ValidationHelper.htm)
[Tessa.Applications - пространство имён](N_Tessa_Applications.htm)
